---
- name: Install elasticsearch
  yum: 
    name: elasticsearch
    state: latest 
    update_cache: yes

- name: Create elasticsearch config
  template:
    src: elasticsearch.config.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: Restart elasticsearch

- name: Force systemd to reread configs
  systemd: daemon_reload=yes

- name: Start elasticsearch.service
  service:
    name: elasticsearch.service
    state: started
    enabled: yes
